# Generated by Django 5.2.8 on 2025-11-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'autores'},
        ),
    ]
